# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToBuy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToBuy
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'DropDown'
  pod 'SDWebImage', '~> 5.0'
end
